using SharedServices.Models.Achievement;

namespace MyZabbix.Web.Achievements;

public static class MyZabbixAchievements
{
    public static readonly IReadOnlyList<AchievementDef> All = new List<AchievementDef>
    {
        // ── Připojení ─────────────────────────────────────────────────────────
        new("MZ_CONNECT_FIRST",       "První připojení",      "Úspěšně se připoj k Zabbix API",                       "bi-plug",                 15, "Připojení"),
        new("MZ_CONNECT_SETTINGS",    "Nastavení",            "Otevři stránku nastavení",                             "bi-gear",                  5, "Připojení"),
        new("MZ_CONNECT_CUSTOM_URL",  "Vlastní URL",          "Nastav vlastní Zabbix URL",                            "bi-link",                 10, "Připojení"),
        new("MZ_CONNECT_RECONNECT",   "Znovu připojen",       "Připoj se podruhé ke stejnému serveru",                "bi-arrow-clockwise",      10, "Připojení"),
        new("MZ_CONNECT_MULTI_SERVER","Multi-server",         "Připoj se ke 2 různým Zabbix serverům",                "bi-server",               25, "Připojení"),
        new("MZ_CONNECT_STABLE",      "Stabilní připojení",   "Buď připojen po dobu 1 hodiny",                        "bi-wifi",                 20, "Připojení"),
        new("MZ_CONNECT_VERIFIED",    "Ověřené spojení",      "Ověř připojení pomocí API testu",                      "bi-check-circle",         15, "Připojení"),
        new("MZ_CONNECT_DASHBOARD",   "Domovská stránka",     "Navštiv dashboard po připojení",                       "bi-house",                 5, "Připojení"),
        new("MZ_CONNECT_SAVE",        "Uložená konfigurace",  "Ulož nastavení připojení",                             "bi-floppy",               10, "Připojení"),
        new("MZ_CONNECT_FAST",        "Rychlé připojení",     "Připoj se za méně než 3 sekundy",                      "bi-lightning",            15, "Připojení"),
        new("MZ_CONNECT_VERSION",     "Verze API",            "Zkontroluj verzi Zabbix API",                          "bi-info-circle",          10, "Připojení"),
        new("MZ_CONNECT_TOKEN",       "API Token",            "Použij API token pro autentizaci",                     "bi-key",                  20, "Připojení"),
        new("MZ_CONNECT_REVISIT",     "Pravidelný",           "Připoj se 5×",                                         "bi-repeat",               15, "Připojení"),
        new("MZ_CONNECT_LOGOUT",      "Odpojení",             "Bezpečně se odpoj od serveru",                         "bi-box-arrow-right",       5, "Připojení"),
        new("MZ_CONNECT_MORNING",     "Ranní kontrola",       "Připoj se ráno před 9. hodinou",                       "bi-sunrise",              10, "Připojení"),

        // ── Hosts ─────────────────────────────────────────────────────────────
        new("MZ_HOST_FIRST",          "První host",           "Zobraz prvního hosta",                                 "bi-pc-display",           10, "Hosts"),
        new("MZ_HOST_SEARCH",         "Hledač hostů",         "Prohledej seznam hostů",                               "bi-search",                5, "Hosts"),
        new("MZ_HOST_DETAIL",         "Detail hosta",         "Otevři detail konkrétního hosta",                      "bi-info-circle",          10, "Hosts"),
        new("MZ_HOST_10",             "10 hostů",             "Monitoruj 10+ hostů",                                  "bi-pc-display-horizontal",15, "Hosts"),
        new("MZ_HOST_50",             "50 hostů",             "Monitoruj 50+ hostů",                                  "bi-hdd-network",          30, "Hosts"),
        new("MZ_HOST_100",            "100 hostů",            "Monitoruj 100+ hostů",                                 "bi-diagram-3",            50, "Hosts"),
        new("MZ_HOST_ENABLED",        "Aktivní host",         "Zobraz aktivního hosta",                               "bi-check-circle-fill",    10, "Hosts"),
        new("MZ_HOST_DISABLED",       "Deaktivovaný",         "Zobraz deaktivovaného hosta",                          "bi-x-circle",              5, "Hosts"),
        new("MZ_HOST_GROUP",          "Skupina hostů",        "Filtruj hosty podle skupiny",                          "bi-collection",           10, "Hosts"),
        new("MZ_HOST_PAGE_5",         "Pátá stránka",         "Přejdi na 5. stránku hostů",                           "bi-5-circle",             10, "Hosts"),
        new("MZ_HOST_AVAILABILITY",   "Dostupnost",           "Zkontroluj dostupnost hosta",                          "bi-activity",             15, "Hosts"),
        new("MZ_HOST_INTERFACES",     "Rozhraní",             "Zobraz síťová rozhraní hosta",                         "bi-ethernet",             10, "Hosts"),
        new("MZ_HOST_TEMPLATES",      "Šablony",              "Zobraz šablony aplikované na host",                    "bi-file-earmark-code",    15, "Hosts"),
        new("MZ_HOST_PROBLEMS_VIEW",  "Problémy hosta",       "Zobraz problémy konkrétního hosta",                    "bi-exclamation-triangle", 15, "Hosts"),
        new("MZ_HOST_500",            "500 hostů",            "Monitoruj 500+ hostů",                                 "bi-building",             75, "Hosts"),
        new("MZ_HOST_MONITOR_ALL",    "Všechno monitoruji",   "Zobraz všechny hosty bez filtru",                      "bi-eye",                  10, "Hosts"),
        new("MZ_HOST_CRITICAL",       "Kritický host",        "Najdi hosta s kritickým problémem",                    "bi-exclamation-octagon",  20, "Hosts"),
        new("MZ_HOST_WINDOWS",        "Windows server",       "Zobraz hosta se systémem Windows",                     "bi-windows",              10, "Hosts"),
        new("MZ_HOST_LINUX",          "Linux server",         "Zobraz hosta se systémem Linux",                       "bi-terminal",             10, "Hosts"),
        new("MZ_HOST_NETWORK",        "Síťové zařízení",      "Zobraz síťové zařízení v hostech",                     "bi-router",               15, "Hosts"),
        new("MZ_HOST_REVISIT",        "Host maniak",          "Navštiv stránku hostů 5×",                             "bi-arrow-repeat",         10, "Hosts"),

        // ── Problémy ──────────────────────────────────────────────────────────
        new("MZ_PROB_FIRST",          "První problém",        "Zobraz první problém",                                 "bi-bug",                  10, "Problémy"),
        new("MZ_PROB_SEARCH",         "Hledač problémů",      "Prohledej problémy",                                   "bi-search",                5, "Problémy"),
        new("MZ_PROB_CSV",            "Export problémů",      "Exportuj problémy do CSV",                             "bi-download",             10, "Problémy"),
        new("MZ_PROB_SEVERITY_FILTER","Filtr závažnosti",     "Filtruj problémy podle závažnosti",                    "bi-funnel",                5, "Problémy"),
        new("MZ_PROB_CRITICAL",       "Kritický problém",     "Zobraz problém s kritickou závažností",                "bi-exclamation-octagon",  15, "Problémy"),
        new("MZ_PROB_HIGH",           "Vysoká závažnost",     "Zobraz problém s vysokou závažností",                  "bi-exclamation-triangle-fill", 10, "Problémy"),
        new("MZ_PROB_100",            "100 problémů",         "Databáze obsahuje 100+ problémů",                      "bi-shield-x",             25, "Problémy"),
        new("MZ_PROB_1000",           "1 000 problémů",       "Databáze obsahuje 1000+ problémů",                     "bi-fire",                 50, "Problémy"),
        new("MZ_PROB_RESOLVED",       "Vyřešeno",             "Zobraz vyřešené problémy",                             "bi-check2-all",           15, "Problémy"),
        new("MZ_PROB_TRIGGER_FILTER", "Filtr trigger",        "Filtruj problémy podle triggeru",                      "bi-bell",                 10, "Problémy"),
        new("MZ_PROB_HOST_FILTER",    "Filtr hosta",          "Filtruj problémy podle hosta",                         "bi-pc-display",           10, "Problémy"),
        new("MZ_PROB_MULTIPLE_SEV",   "Různé závažnosti",     "Zobraz problémy všech závažností",                     "bi-layers",               20, "Problémy"),
        new("MZ_PROB_PAGE_5",         "5. stránka",           "Přejdi na 5. stránku problémů",                        "bi-5-circle",             10, "Problémy"),
        new("MZ_PROB_EXPORT_1000",    "Velký export",         "Exportuj 1000+ problémů",                              "bi-file-earmark-arrow-down", 25, "Problémy"),
        new("MZ_PROB_DURATION",       "Dlouhý problém",       "Zobraz problém trvající 24+ hodin",                    "bi-hourglass-bottom",     20, "Problémy"),
        new("MZ_PROB_DISASTER",       "Katastrofa",           "Zobraz problém s úrovní Disaster",                     "bi-radioactive",          30, "Problémy"),
        new("MZ_PROB_INFO",           "Informační",           "Zobraz problém s úrovní Information",                  "bi-info-circle",           5, "Problémy"),
        new("MZ_PROB_WARNING",        "Varování",             "Zobraz problém s úrovní Warning",                      "bi-exclamation-diamond",   5, "Problémy"),
        new("MZ_PROB_AVERAGE",        "Průměrný",             "Zobraz problém s úrovní Average",                      "bi-dash-circle",          10, "Problémy"),
        new("MZ_PROB_REVISIT",        "Bdělý správce",        "Navštiv stránku problémů 5×",                          "bi-eye",                  15, "Problémy"),
        new("MZ_PROB_ZERO",           "Čistý štít",           "Systém nemá žádné aktuální problémy",                  "bi-shield-check",         40, "Problémy"),
        new("MZ_PROB_10000",          "10 000 problémů",      "Databáze obsahuje 10000+ problémů",                    "bi-database-x",           75, "Problémy"),
        new("MZ_PROB_CHART",          "Graf problémů",        "Zobraz chart závažností na dashboardu",                "bi-bar-chart",            15, "Problémy"),
        new("MZ_PROB_ACKNOWLEDGED",   "Potvrzený",            "Zobraz potvrzený problém",                             "bi-person-check",         10, "Problémy"),
        new("MZ_PROB_MULTI_HOST",     "Více hostů",           "Zobraz problémy z 5+ různých hostů",                   "bi-diagram-2",            20, "Problémy"),

        // ── Dashboard ─────────────────────────────────────────────────────────
        new("MZ_DASH_VISIT",          "Dashboard",            "Navštiv hlavní dashboard",                             "bi-house",                 5, "Dashboard"),
        new("MZ_DASH_CHART",          "Graf závažností",      "Prohlédni chart závažností",                           "bi-bar-chart-fill",       10, "Dashboard"),
        new("MZ_DASH_STATS",          "Přehled",              "Zobraz celkové statistiky monitoringu",                 "bi-graph-up",             10, "Dashboard"),
        new("MZ_DASH_REVISIT",        "Pravidelný monitor",   "Navštiv dashboard 10×",                                "bi-arrow-repeat",         15, "Dashboard"),
        new("MZ_DASH_DARK",           "Temný monitor",        "Přepni na tmavý režim",                                "bi-moon-fill",            10, "Dashboard"),
        new("MZ_DASH_THEME",          "Vlastní vzhled",       "Změň téma aplikace",                                   "bi-palette",               5, "Dashboard"),
        new("MZ_DASH_RESPONSIVE",     "Responzivní",          "Zobraz dashboard na mobilu",                           "bi-phone",                10, "Dashboard"),
        new("MZ_DASH_NAVMENU",        "Navigátor",            "Použij boční menu k navigaci",                         "bi-layout-sidebar",        5, "Dashboard"),
        new("MZ_DASH_ALL_PAGES",      "Průzkumník",           "Navštiv všechny stránky aplikace",                     "bi-map",                  15, "Dashboard"),
        new("MZ_DASH_FIRST_MORNING",  "Ranní přehled",        "Zkontroluj dashboard ráno",                            "bi-sunrise",              10, "Dashboard"),

        // ── Speciální ─────────────────────────────────────────────────────────
        new("MZ_SPECIAL_WELCOME",     "Vítej!",               "Otevři aplikaci poprvé",                               "bi-door-open",             5, "Speciální"),
        new("MZ_SPECIAL_ACHI_PAGE",   "Sběratel",             "Otevři stránku achievementů",                          "bi-trophy-fill",           5, "Speciální"),
        new("MZ_SPECIAL_ACHI_10",     "10 achievementů",      "Odemkni 10 achievementů",                              "bi-award",                20, "Speciální"),
        new("MZ_SPECIAL_ACHI_25",     "25 achievementů",      "Odemkni 25 achievementů",                              "bi-award-fill",           40, "Speciální"),
        new("MZ_SPECIAL_ACHI_50",     "50 achievementů",      "Odemkni 50 achievementů",                              "bi-stars",                75, "Speciální"),
        new("MZ_SPECIAL_ACHI_ALL",    "Platinový admin",      "Odemkni všechny achievementy",                         "bi-gem",                 200, "Speciální"),
        new("MZ_SPECIAL_500_PTS",     "500 bodů",             "Nashromáždi 500 bodů",                                 "bi-circle-fill",          30, "Speciální"),
        new("MZ_SPECIAL_1000_PTS",    "1 000 bodů",           "Nashromáždi 1000 bodů",                                "bi-pentagon-fill",        60, "Speciální"),
        new("MZ_SPECIAL_NIGHT_OWL",   "Noční správce",        "Použij aplikaci po půlnoci",                           "bi-moon-stars",           15, "Speciální"),
        new("MZ_SPECIAL_WEEKEND",     "Víkendový admin",      "Zkontroluj systém o víkendu",                          "bi-calendar2-week",       10, "Speciální"),
        new("MZ_SPECIAL_POWER_USER",  "Pokročilý uživatel",   "Použij vyhledávání, filtry i export",                  "bi-person-gear",          30, "Speciální"),
        new("MZ_SPECIAL_MOBILE",      "Mobilní admin",        "Otevři aplikaci na mobilním zařízení",                 "bi-phone",                15, "Speciální"),
        new("MZ_SPECIAL_FIRST_WEEK",  "Týdenní dohled",       "Používej aplikaci 7 dní",                              "bi-calendar-week",        40, "Speciální"),
        new("MZ_SPECIAL_HEALTHY",     "Zdravý systém",        "Monitoruj systém bez kritických problémů",             "bi-heart-pulse",          35, "Speciální"),
        new("MZ_SPECIAL_ZABBIX_PRO",  "Zabbix Pro",           "Odemkni 75+ achievementů",                             "bi-shield-fill-check",   100, "Speciální"),
    };
}
